### ISSUE TITLE
circular import

### ISSUE THREAD

**Issue by FKClose9** [QiujieDong/NeurCADRecon#2]
When i input "python pre_data.py",i get:
Traceback (most recent call last):
  File "pre_data.py", line 10, in <module>
    import utils.utils as utils
  File "/mnt/d/NeurCADRecon/pre_processing/../utils/utils.py", line 29, in <module>
    import matplotlib.pyplot as plt
  File "/mnt/d/miniconda3/envs/NeurCAD_env/lib/python3.8/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/mnt/d/miniconda3/envs/NeurCAD_env/lib/python3.8/site-packages/matplotlib/cbook.py", line 32, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (/mnt/d/miniconda3/envs/NeurCAD_env/lib/python3.8/site-packages/matplotlib/__init__.py)
How can i fix it, please?

**Comment by QiujieDong** [comment]
> When i input "python pre_data.py",i get: Traceback (most recent call last): File "pre_data.py", line 10, in import utils.utils as utils File "/mnt/d/NeurCADRecon/pre_processing/../utils/utils.py", line 29, in import matplotlib.pyplot as plt File "/mnt/d/miniconda3/envs/NeurCAD_env/lib/python3.8/site-packages/matplotlib/**init**.py", line 159, in from . import _api, _version, cbook, _docstring, rcsetup File "/mnt/d/miniconda3/envs/NeurCAD_env/lib/python3.8/site-packages/matplotlib/cbook.py", line 32, in from matplotlib import _api, _c_internal_utils ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (/mnt/d/miniconda3/envs/NeurCAD_env/lib/python3.8/site-packages/matplotlib/**init**.py) How can i fix it, please?

Hi, @FKClose9,

I re-tested the code and it does not have the problem you mentioned. I think the following BBS may solve your problem.

https://discourse.matplotlib.org/t/cannot-import-name-c-internal-utils-from-matplotlib/22644

https://stackoverflow.com/questions/73124060/importerror-cannot-import-name-c-internal-utils-from-partially-initialized-m

**Comment by FKClose9** [comment]
When i execute "python pre_data.py" command, I have solved one problem after another, but there are still many new configuration problems, can you give more specific configuration commands, or the version of each module can also be andi really want to run your code.Thanks for response!

**Comment by QiujieDong** [comment]
> When i execute "python pre_data.py" command, I have solved one problem after another, but there are still many new configuration problems, can you give more specific configuration commands, or the version of each module can also be andi really want to run your code.Thanks for response!

Hi, @FKClose9,

My environment in the server: 
Ubuntu 22.04
Rtx 4090,
Python 3.7
CUDA 12.2
Pytorch 1.13.0

--Packages
matplotlib==3.5.3
numba==0.56.4
numpy==1.21.5
open3d==0.17.0
pandas==1.3.5
Pillow==10.4.0
plotly==5.18.0
PyMCubes==0.1.4
scikit_image==0.19.3
scikit_learn==1.0.2
scipy==1.7.3
tensorboardX==2.6.2.2
tensorboardX==2.6.2.2
torch==1.13.0
torchinfo==1.8.0
tqdm==4.66.1
trimesh==4.0.5

**Comment by FKClose9** [comment]
Oh,thanks very much!
